# Copyright (c) 2007-2009 Google Inc.
# Copyright (c) 2006-2007 Jaiku Ltd.
# Copyright (c) 2002-2006 Mika Raento and Renaud Petit
#
# This software is licensed at your choice under either 1 or 2 below.
#
# 1. Perl (Artistic) License
#
# This library is free software; you can redistribute it and/or modify it
# under the same terms as Perl itself.
#
# 2. Gnu General Public license 2.0
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
#
# This file is part of the JaikuEngine mobile frontend.
package Jaiku::Settings;

use constant {
SETTING_WAP_AP	=> 1,
SETTING_PHONENO => 2,
SETTING_IP_AP   => 3,
SETTING_LAST_COMMLOG_UPLOAD => 4,
SETTING_CELLMAP_CLOSED => 5,
SETTING_BASEDB_VERSION => 6,
SETTING_JABBER_NICK => 7,
SETTING_JABBER_PASS => 8,
SETTING_PRESENCE_ENABLE => 9,
SETTING_LAST_BASE_STAMP => 10,
SETTING_MEDIA_UPLOAD_ENABLE => 11,
SETTING_UPLOAD_URLBASE => 12,
SETTING_PREV_BASE => 13,
SETTING_PREV_BASE_STAMP => 14,
SETTING_UPLOAD_TAG => 15,
SETTING_OPTIONS_ENABLE => 16,
SETTING_DELETE_UPLOADED	=> 17,
SETTING_LOGGING_ENABLE	=> 18,
SETTING_LOCATIONSERVICE_ENABLE => 19,
SETTING_BT_SCAN_INTERVAL => 20,
SETTING_RECORD_ALL => 21,
SETTING_LOG_UPLOAD_ENABLE => 22,
SETTING_TAG_ONLY => 23,
SETTING_PROMPT_FOR_NAMES => 24,
SETTING_UPLOAD_PROMPT_TYPE => 25,
SETTING_PUBLISH_URLBASE => 26,
SETTING_VIBRATE_ONLY => 27,
SETTING_GPS_BT_ADDR => 28,
SETTING_GPS_LOG_TIME => 29,
SETTING_GPS_BT_PORT => 30,
SETTING_PUBLISH_AUTHOR => 31,
SETTING_SNAPSHOT_ON_SMS => 32,
SETTING_PUBLISH_SCRIPT => 33,
SETTING_UPLOAD_SCRIPT => 34,
SETTING_IGNORE_NOTIFICATIONS => 35,
SETTING_BT_AP => 36,
SETTING_BT_DEV_ADDR => 37,
SETTING_BT_DEV_NAME => 38,
SETTING_CURRENT_AP => 39,
SETTING_USE_MMC => 40,
SETTING_RECORD_TIME => 41,
SETTING_PROXY => 42,
SETTING_PROXY_PORT => 43,
SETTING_CONTEXTNW_HOST => 44,
SETTING_CONTEXTNW_PORT => 45,
SETTING_CONTEXTNW_ENABLED => 46,
SETTING_OWN_DESCRIPTION => 47,
SETTING_OWN_DESCRIPTION_TIME => 48,
SETTING_ALLOW_ROAMING => 49,
SETTING_RIGHT_SOFTKEY_CONTEXT => 50,
SETTING_PUBLISH_TYPE => 51,
SETTING_PUBLISH_USERNAME => 52,
SETTING_PUBLISH_PASSWORD => 53,
SETTING_ENABLE_LOCA_BLUEJACK => 54,
SETTING_LOCA_BLUEJACK_MAX_MESSAGES => 55,
SETTING_LOCA_BLUEJACK_MAX_RETRIES => 56,
SETTING_LOCA_BLUEJACK_CONNECT_COUNT => 57,
SETTING_PROJECT_NAME => 58,
SETTING_LOCA_BLUEJACK_MESSAGE_TIMEOUT => 59,
SETTING_VISUALCODES_URLBASE => 60,
SETTING_VISUALCODES_SCRIPT => 61,
SETTING_FLICKR_AUTH => 62,
SETTING_PLAYBACK_VOLUME => 63,
SETTING_PUBLISH_SHARING => 64,
SETTING_PUBLISH_AUTOTAGS => 65,
SETTING_CALENDAR_SHARING => 66,
SETTING_SHOW_AUTOTAGS => 67,
SETTING_SNAPSHOT_INTERVAL => 68,
SETTING_SHOW_TAGS => 69,
SETTING_FIXED_PRIVACY => 70,
SETTING_LAST_CONNECTION_TIME => 71,
SETTING_LAST_CONNECTION_BYTECOUNT => 72,
SETTING_LAST_TIMESYNC => 73,
SETTING_AUTH_SEQ => 74,
SETTING_WINS_IMEI => 75,
SETTING_PRESENCE_EXPIRATION_TIME => 76,
SETTING_JABBER_ADDR => 77 ,
SETTING_JABBER_PORT => 78 ,
SETTING_PROFILE_BEFORE_SLEEP => 79,
SETTING_WENT_TO_SLEEP => 80,
SETTING_JABBER_PASS_SHA1 => 81,
SETTING_DEVICE_ID => 82,
SETTING_USER_EMAIL => 83,
SETTING_USER_FIRSTNAME => 84,
SETTING_USER_LASTNAME => 85,
SETTING_ALLOW_NETWORK_ACCESS => 86,
SETTING_ALLOW_NETWORK_ONCE => 87,
SETTING_ACCEPTED_PRIVACY_STMT_VERSION => 88,
SETTING_ACCEPTED_NETWORK_ACCESS => 89,
SETTING_IDENTIFICATION_ERROR => 90,
SETTING_LAST_CONNECTION_SUCCESS => 91,
SETTING_LAST_CONNECTION_ATTEMPT => 92,
SETTING_LAST_CONNECTION_ERROR => 93,
SETTING_LAST_CONNECTION_REQUEST => 94,
SETTING_LATEST_CONNECTION_REQUEST => 95,
SETTING_PROGRESS_INCOMING => 96,
SETTING_PROGRESS_OUTGOING => 97,

MAX_ADDRESS_LEN => 30,
MAX_URL_LEN	=> 100,

MEDIA_PUBLISHER_DISABLED => 0,
MEDIA_PUBLISHER_CL => 1,
MEDIA_PUBLISHER_CM => 2,

MEDIA_PUBLISH_CONTEXT => 0,
MEDIA_PUBLISH_FLICKR => 1,

SHARE_CALENDAR_FULL => 0,
SHARE_CALENDAR_FREEBUSY => 1,
SHARE_CALENDAR_NONE => 2,

};

1;
